"use client";
import { useEffect, useRef, useState } from "react";
import * as echarts from "echarts";

const API=process.env.NEXT_PUBLIC_API_BASE||"http://localhost:8000";
export default function Detail({code,date,onBack}:{code:string;date:string;onBack:()=>void}){const [item,setItem]=useState<any>(null);const [messages,setMessages]=useState<any[]>([]);const chartRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{Promise.all([fetch(`${API}/api/selections/${code}?date=${date}`).then(r=>r.json()),fetch(`${API}/api/stocks/${code}/messages`).then(r=>r.json())]).then(([i,m])=>{setItem(i);setMessages(m.items||[])})},[code,date]);
 useEffect(()=>{fetch(`${API}/api/stocks/${code}/kline`).then(r=>r.json()).then(data=>{if(!chartRef.current)return;const chart=echarts.init(chartRef.current);const x=data.items.map((p:any)=>p.date);chart.setOption({animation:false,grid:{left:8,right:18,top:18,bottom:28,containLabel:true},tooltip:{trigger:"axis"},xAxis:{type:"category",data:x,axisLine:{lineStyle:{color:"#dfe7df"}},axisLabel:{color:"#6e7c77"}},yAxis:{scale:true,splitLine:{lineStyle:{color:"#edf1ec"}},axisLabel:{color:"#6e7c77"}},series:[{type:"line",name:"收盘",data:data.items.map((p:any)=>p.close),smooth:true,lineStyle:{color:"#16845b",width:3},showSymbol:false},{type:"line",name:"MA20",data:data.items.map((p:any)=>p.ma20),smooth:true,lineStyle:{color:"#f4bf61",width:2},showSymbol:false}]});return()=>chart.dispose()})},[code]);
 if(!item)return <main className="shell"><button className="back" onClick={onBack}>← 返回选股台</button><div className="loading">正在读取股票详情…</div></main>;
 return <main className="shell"><button className="back" onClick={onBack}>← 返回选股台</button><div className="hero"><div><div className="eyebrow">{item.code} / {item.trade_date}</div><h2>{item.name}</h2><p>{item.industry||"未分类"} · {item.strategy_name}</p></div><div className="score" style={{width:58,height:40,fontSize:18}}>{item.score}</div></div><div className="detail"><section className="panel detail-card"><div className="panel-head" style={{padding:0,border:0,marginBottom:12}}><h3>价格走势</h3><span>DAILY · 60D</span></div><div ref={chartRef} className="chart"/></section><section className="panel detail-card"><div className="panel-head" style={{padding:0,border:0}}><h3>入选依据</h3><span>WHY</span></div><div style={{margin:"20px 0"}}>{(item.reasons||[]).map((r:string)=><span className="tag" key={r}>{r}</span>)}</div><h3 style={{fontSize:14}}>指标快照</h3>{Object.entries(item.indicators||{}).map(([k,v])=><div key={k} style={{display:"flex",justifyContent:"space-between",padding:"12px 0",borderBottom:"1px solid #edf1ec",fontSize:13}}><span style={{color:"#6e7c77"}}>{k}</span><b>{String(v)}</b></div>)}</section></div><section className="panel detail-card" style={{marginTop:18}}><div className="panel-head" style={{padding:0,border:0,marginBottom:6}}><h3>相关新闻</h3><span>MESSAGES</span></div>{messages.map((m:any,i)=><div className="message" key={i}><h4>{m.title}</h4><p>{m.source} · {m.published_at?.slice(0,16).replace("T"," ")}</p><p>{m.summary}</p></div>)}</section></main>}
