"use client";

import { useEffect, useMemo, useState } from "react";
import Detail from "./detail";

const API = process.env.NEXT_PUBLIC_API_BASE || "http://localhost:8000";
type Item = { code:string; name:string; trade_date:string; price?:number; change_pct?:number; score?:number; strategy_name:string; industry?:string; reasons:string[]; indicators:Record<string, unknown> };

export default function Home(){
  const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [items,setItems]=useState<Item[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [running,setRunning]=useState(false); const [selected,setSelected]=useState<string|null>(null); const [query,setQuery]=useState(""); const [strategy,setStrategy]=useState("全部策略");
  const load=async()=>{setLoading(true);setError("");try{const r=await fetch(`${API}/api/selections?date=${date}`);if(!r.ok)throw new Error("无法读取选股结果");const data=await r.json();setItems(data.items||[])}catch(e){setError("后端暂未连接。请先启动 FastAPI；启动后点击刷新即可加载结果。")}finally{setLoading(false)}};
  useEffect(()=>{load()},[date]);
  const run=async()=>{setRunning(true);try{await fetch(`${API}/api/jobs/run-selection`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({trade_date:date})});await load()}catch{setError("选股任务启动失败，请检查后端是否运行")}finally{setRunning(false)}};
  const strategies=useMemo(()=>["全部策略",...Array.from(new Set(items.map(i=>i.strategy_name)))],[items]);
  const filtered=items.filter(i=>(strategy==="全部策略"||i.strategy_name===strategy)&&(`${i.code}${i.name}${i.industry||""}`.includes(query)));
  if(selected)return <Detail code={selected} date={date} onBack={()=>setSelected(null)}/>;
  return <main className="shell"><header className="topbar"><div className="brand"><div className="logo">选</div><div><div className="eyebrow">daily signal desk</div><h1>每日选股台</h1></div></div><div className="status"><i/>本机工作区 · 数据仅供研究</div></header><section className="hero"><div><div className="eyebrow">{date} / close review</div><h2>今天，市场<br/><em>留下了什么？</em></h2><p>把策略信号、行情与消息，收拢在一个清晰的工作台。</p></div><div className="actions"><input className="btn" type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="btn primary" onClick={run} disabled={running}>{running?"运行中…":"立即运行选股"}</button></div></section>{error&&<div className="error">{error}</div>}<section className="metrics"><div className="metric"><small>入选股票</small><strong>{items.length}</strong><span>只</span></div><div className="metric"><small>平均策略分</small><strong>{items.length?(items.reduce((a,i)=>a+(i.score||0),0)/items.length).toFixed(1):"—"}</strong><span>/ 100</span></div><div className="metric"><small>上涨信号</small><strong>{items.filter(i=>(i.change_pct||0)>0).length}</strong><span className="positive">↑</span></div><div className="metric"><small>数据时间</small><strong style={{fontSize:20}}>收盘后</strong><span>同步</span></div></section><div className="toolbar"><input placeholder="搜索股票代码、名称或行业" value={query} onChange={e=>setQuery(e.target.value)}/><select value={strategy} onChange={e=>setStrategy(e.target.value)}>{strategies.map(s=><option key={s}>{s}</option>)}</select><button className="btn" onClick={load}>刷新结果</button></div><section className="panel table-panel"><div className="panel-head"><h3>今日信号</h3><span>{filtered.length} RESULTS · SCORE DESC</span></div>{loading?<div className="loading">正在读取选股结果…</div>:!filtered.length?<div className="empty">这一天还没有选股结果。你可以运行一次策略，或换一个日期。</div>:<table><thead><tr><th>股票</th><th>现价</th><th>涨跌</th><th>策略</th><th>理由</th><th>评分</th></tr></thead><tbody>{filtered.map(i=><tr key={i.code} onClick={()=>setSelected(i.code)}><td><div className="stock"><div><b>{i.name}</b><small>{i.code} · {i.industry||"未分类"}</small></div></div></td><td>{i.price??"—"}</td><td className={(i.change_pct||0)>=0?"positive":"negative"}>{i.change_pct==null?"—":`${i.change_pct>0?"+":""}${i.change_pct.toFixed(2)}%`}</td><td><span className="tag">{i.strategy_name}</span></td><td className="reason">{i.reasons?.[0]||"—"}</td><td><span className="score">{i.score??"—"}</span></td></tr>)}</tbody></table>}</section></main>
}
