"""Adapter for the user-owned D-drive authoritative stock screener.

This module never calculates candidates itself.  It runs the official Node.js
entry point and converts its newly generated HTML report to the existing local
import contract.  The D-drive assets remain read-only.
"""

from __future__ import annotations

import argparse
from datetime import date
from html.parser import HTMLParser
import json
import os
from pathlib import Path
import re
import subprocess
from typing import Any

from app.data.market_data import fill_missing_selection_prices


AUTHORITATIVE_STRATEGY_NAME = "超短线技术共振"
DEFAULT_SCREENER_DIR = Path(r"D:\Program Files\xuangu")
REPORT_DIRECTORY_NAME = "result"
REPORT_GLOB = "选股结果*.html"


class LocalSelectionDataError(RuntimeError):
    """The authoritative local screener could not produce a usable report."""


class _ReportTableParser(HTMLParser):
    """Extract table cell text without executing or trusting HTML content."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.rows: list[list[str]] = []
        self._row: list[str] | None = None
        self._cell: list[str] | None = None

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag == "tr":
            self._row = []
        elif tag in {"td", "th"} and self._row is not None:
            self._cell = []

    def handle_data(self, data: str) -> None:
        if self._cell is not None:
            self._cell.append(data)

    def handle_endtag(self, tag: str) -> None:
        if tag in {"td", "th"} and self._row is not None and self._cell is not None:
            self._row.append(" ".join("".join(self._cell).split()))
            self._cell = None
        elif tag == "tr" and self._row is not None:
            if self._row:
                self.rows.append(self._row)
            self._row = None


def _screener_dir() -> Path:
    return Path(os.getenv("XUANGU_SCREENER_DIR", str(DEFAULT_SCREENER_DIR))).expanduser()


def _number(text: str, field: str) -> float:
    match = re.search(r"[-+]?\d+(?:\.\d+)?", text.replace(",", ""))
    if not match:
        raise LocalSelectionDataError(f"官方报告缺少有效{field}: {text!r}")
    return float(match.group())


def _report_trade_date(html: str, path: Path) -> str:
    match = re.search(r"生成时间[：:]\s*(\d{4})-(\d{2})-(\d{2})", html)
    if not match:
        match = re.search(r"(\d{4})年(\d{2})月(\d{2})日", path.name)
    if not match:
        raise LocalSelectionDataError(f"无法从官方报告识别交易日: {path.name}")
    return "-".join(match.groups())


def _validate_trade_date(value: str) -> str:
    try:
        return date.fromisoformat(value).isoformat()
    except (TypeError, ValueError) as exc:
        raise LocalSelectionDataError("trade_date 必须为 YYYY-MM-DD 格式") from exc


def parse_official_report(path: Path, expected_trade_date: str | None = None) -> list[dict[str, Any]]:
    """Parse a report generated by ``stock_screener.js`` into import items."""
    try:
        html = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise LocalSelectionDataError(f"无法读取官方选股报告: {path}") from exc
    trade_date = _report_trade_date(html, path)
    if expected_trade_date is not None and trade_date != _validate_trade_date(expected_trade_date):
        raise LocalSelectionDataError(
            f"指定导入日期与官方报告不一致: 指定 {expected_trade_date}，报告 {trade_date}"
        )
    parser = _ReportTableParser()
    parser.feed(html)

    items: list[dict[str, Any]] = []
    for row in parser.rows:
        # #, code, name, industry, board count, turnover, change, volume ratio,
        # base, bonus, deduction, final score, level, rating, original detail.
        if len(row) < 15 or not re.fullmatch(r"\d{6}", row[1]):
            continue
        code, name, industry = row[1], row[2], row[3] or None
        board_count = int(_number(row[4], "连板数"))
        turnover = _number(row[5], "换手率")
        change_pct = _number(row[6], "涨跌幅")
        volume_ratio = _number(row[7], "量比")
        base_score = _number(row[8], "基础分")
        bonus_score = _number(row[9], "加分")
        deduction_score = _number(row[10], "扣分")
        score = _number(row[11], "总分")
        if not 0 <= score <= 100:
            raise LocalSelectionDataError(f"官方报告总分超出导入范围: {code}={score}")
        level, rating, details = row[12], row[13], row[14]
        indicators = {
            "turnover": turnover,
            "board_count": board_count,
            "volume_ratio_ma5": volume_ratio,
            "base_score": base_score,
            "bonus_score": bonus_score,
            "deduction_score": deduction_score,
            "rating_level": level,
            "rating": rating,
            "official_details": details,
        }
        items.append({
            "code": code,
            "name": name,
            "trade_date": trade_date,
            "strategy_name": AUTHORITATIVE_STRATEGY_NAME,
            "score": score,
            # The official HTML has no closing-price column.  Do not invent one.
            "price": None,
            "change_pct": change_pct,
            "industry": industry,
            "turnover": turnover,
            "board_count": board_count,
            "reasons": [f"评级：{level}（{rating}）", details],
            "indicators": indicators,
        })
    if not items:
        raise LocalSelectionDataError(f"官方报告未包含可导入的选股行: {path.name}")
    # The report is the sole authority for its candidates, scores and metrics.
    # It omits a price column, so the data layer may only enrich the already
    # parsed rows with that report session's daily close.
    return fill_missing_selection_prices(items)


def run_selection_from_report(report_path: str | Path, trade_date: str) -> list[dict[str, Any]]:
    """Parse one explicit official report without running the D-drive script."""
    path = Path(report_path).expanduser()
    if not path.is_file():
        raise LocalSelectionDataError(f"指定官方报告不存在: {path}")
    return parse_official_report(path, expected_trade_date=trade_date)


def _newest_report(report_dir: Path, before: dict[Path, int]) -> Path:
    candidates = [path for path in report_dir.glob(REPORT_GLOB) if path.is_file()]
    created_or_changed = [path for path in candidates if path.stat().st_mtime_ns > before.get(path, -1)]
    if not created_or_changed:
        raise LocalSelectionDataError("官方脚本未生成或更新选股 HTML 报告")
    return max(created_or_changed, key=lambda path: path.stat().st_mtime_ns)


def run_selection(trade_date: str | None = None, report_path: str | Path | None = None) -> list[dict[str, Any]]:
    """Execute the official D-drive screener and parse its newly written report.

    A process-scoped ``XUANGU_OFFICIAL_REPORT_PATH`` selects parse-only mode
    for a known report. Without it, weekend invocations stop before Node.js.
    """
    requested = _validate_trade_date(trade_date) if trade_date else date.today().isoformat()
    explicit_report = report_path or os.getenv("XUANGU_OFFICIAL_REPORT_PATH", "").strip()
    if explicit_report:
        return run_selection_from_report(explicit_report, requested)
    if date.fromisoformat(requested).weekday() >= 5:
        raise LocalSelectionDataError(f"非交易日，未执行官方选股脚本: {requested}")
    root = _screener_dir()
    entry = root / "stock_screener.js"
    report_dir = root / REPORT_DIRECTORY_NAME
    if not entry.is_file():
        raise LocalSelectionDataError(f"未找到官方脚本入口: {entry}")
    if not report_dir.is_dir():
        raise LocalSelectionDataError(f"未找到官方结果目录: {report_dir}")
    before = {path: path.stat().st_mtime_ns for path in report_dir.glob(REPORT_GLOB) if path.is_file()}
    try:
        completed = subprocess.run(
            ["node", entry.name], cwd=root, text=True, capture_output=True, timeout=15 * 60, check=False,
        )
    except FileNotFoundError as exc:
        raise LocalSelectionDataError("无法执行官方脚本：未找到 Node.js") from exc
    except subprocess.TimeoutExpired as exc:
        raise LocalSelectionDataError("官方选股脚本执行超时（15分钟）") from exc
    if completed.returncode:
        detail = (completed.stderr or completed.stdout or "").strip()[-1000:]
        raise LocalSelectionDataError(f"官方选股脚本执行失败（退出码 {completed.returncode}）: {detail}")
    return parse_official_report(_newest_report(report_dir, before), expected_trade_date=requested)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="执行 D 盘官方选股并输出可导入 JSON items")
    parser.add_argument("trade_date", nargs="?", help="运行或校验日期，格式 YYYY-MM-DD")
    parser.add_argument("--report-path", help="只解析指定官方 HTML；不运行 D 盘脚本")
    args = parser.parse_args()
    print(json.dumps(run_selection(args.trade_date, report_path=args.report_path), ensure_ascii=False, indent=2))
